language: node_js

before_script:
  - cp web-dapp/test/server/_utils/server-config-private.js web-dapp/

script:
  - npm run --prefix=blockchain coverage
  - npm test

after_success:
  - npm run coverage
