language: node_js

services:
  - redis-server

env:
  - REACT_APP_POPA_CONTRACT_ADDRESS=0xbc34e0e4cff0643cf7dc5e2e1e8ec55757583c26
  - REACT_APP_PRICE=1
  - REACT_APP_PRICE_SYMBOL=POA

before_script:
  - cp web-dapp/test/server/_utils/server-config-private.js web-dapp/
  - npm install redis

script:
  - npm run --prefix=blockchain coverage
  - npm test

after_success:
  - npm run coverage
